### ISSUE TITLE
compile_role should show module of origin

### ISSUE THREAD

**Issue by ghost** [bodepd/scenario_node_terminus#27]
**puppet scenario compile_role compute** should show the module from which a class originates. In the following, for instance, one needs to know that **cinder** is part of the **cinder** module. This one is easy but still is a guess and sometimes it can be quite difficult to figure out.

<pre>
cinder                     {"cinder::qpid_hostname":"192.168.200.14","cinder::verbose":false,"cinder::rpc_type":"cinder.openstack.common.rpc.impl_kombu","cinder::rabbit_password":"openstack_rabbit_password","cinder::sql_connection":"mysql://cinder:cinder_pass@192.168.200.14/cinder","cinder::rabbit_host":"192.168.200.14","cinder::qpid_password":"openstack_rabbit_password","cinder::qpid_username":"openstack_rabbit_user","cinder::rabbit_userid":"openstack_rabbit_user"}
cinder::volume             {"cinder::volume::package_ensure":"present"}
cinder::volume::rbd        {"cinder::volume::rbd::rbd_secret_uuid":false,"cinder::volume::rbd::rbd_user":"no user","cinder::volume::rbd::rbd_pool":"rbd","cinder::volume::rbd::glance_api_version":"2"}
coe::base                  {"coe::base::controller_hostname":"192.168.200.14","coe::base::build_node_name":"bm0012.the.re","coe::base::openstack_release":"grizzly","coe::base::controller_node_internal":"192.168.200.14","coe::base::package_repo":"cloud_archive"}
lan                        {}
naginator::compute_target  {}
nova                       {"nova::rabbit_userid":"openstack_rabbit_user","nova::qpid_username":"openstack_rabbit_user","nova::qpid_password":"openstack_rabbit_password","nova::rabbit_host":"192.168.200.14","nova::rabbit_password":"openstack_rabbit_password","nova::qpid_hostname":"192.168.200.14","nova::rpc_backend":"nova.openstack.common.rpc.impl_kombu","nova::sql_connection":"mysql://nova:nova_pass@192.168.200.14/nova","nova::glance_api_servers":"192.168.200.14:9292"}
nova::compute              {"nova::compute::enabled":true,"nova::compute::vncserver_proxyclient_address":"%{ipaddress_lan}","nova::compute::force_config_drive":true,"nova::compute::vncproxy_host":"192.168.200.14"}
nova::compute::libvirt     {"nova::compute::libvirt::libvirt_type":"qemu","nova::compute::libvirt::vncserver_listen":"0.0.0.0"}
nova::compute::quantum     {"nova::compute::quantum::libvirt_vif_driver":"nova.virt.libvirt.vif.LibvirtHybridOVSBridgeDriver"}
nova::network::quantum     {"nova::network::quantum::quantum_admin_auth_url":"http://192.168.200.14:35357/v2.0","nova::network::quantum::quantum_url":"http://192.168.200.14:9696","nova::network::quantum::quantum_admin_password":"quantum_pass"}
quantum                    {"quantum::rabbit_password":"openstack_rabbit_password","quantum::qpid_password":"openstack_rabbit_password","quantum::rabbit_host":"192.168.200.14","quantum::rabbit_user":"openstack_rabbit_user","quantum::rpc_backend":"quantum.openstack.common.rpc.impl_kombu","quantum::verbose":false,"quantum::allow_overlapping_ips":true,"quantum::qpid_username":"openstack_rabbit_user","quantum::core_plugin":"quantum.plugins.openvswitch.ovs_quantum_plugin.OVSQuantumPluginV2","quantum::qpid_hostname":"192.168.200.14"}
quantum::agents::ovs       {"quantum::agents::ovs::enable_tunneling":true,"quantum::agents::ovs::bridge_uplinks":"br-ex:wan","quantum::agents::ovs::local_ip":"%{ipaddress_lan}","quantum::agents::ovs::bridge_mappings":["default:br-ex"]}
</pre>

**Comment by bodepd** [comment]
it's all a bit more readable with --render-as yaml.

In the above case, cinder is from the cinder module: https://github.com/stackforge/puppet-cinder/blob/master/manifests/init.pp

Classes are always from the module that matches their namespace.

**Comment by ghost** [comment]
https://github.com/bodepd/grizzly-manifests/blob/master/manifests/core.pp#L153 this is what prompted the creation of this issue, but I now realize it does not qualify as a module. Sorry for the noise.
